app: /Users/gb/Library/Developer/Xcode/DerivedData/CoreDataBooks-cnwgaoyqfwesfvcdiwcrfnsvdcia/Build/Products/Debug-iphonesimulator/CoreDataBooks.app
template: '/Developer/Platforms/iPhoneOS.platform/Developer/Library/Instruments/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate'

devices:   
  iOS Simulator:
    screen: retina_ios5
