app: /Users/gb/Library/Developer/Xcode/DerivedData/CoreDataBooks-cnwgaoyqfwesfvcdiwcrfnsvdcia/Build/Products/Debug-iphonesimulator/CoreDataBooks.app

devices:
    
  iOS Simulator:
    screen: low_ios5

servers:
  backend:
    host: 192.168.1.2
    port: 8080
